### ISSUE TITLE
Hello, can you provide your model with 39.4mAP

### ISSUE THREAD

**Issue by GroundWalker7** [liangheming/faster_rcnnv1#1]
Thanks a lot!

**Comment by liangheming** [comment]
Have Fun!
链接: https://pan.baidu.com/s/1bKttLHMVRR8qu7OqY48arA  密码: 8403

**Comment by liangheming** [comment]
> Thanks a lot!



> Thanks a lot!

Have Fun!
链接: https://pan.baidu.com/s/1bKttLHMVRR8qu7OqY48arA 密码: 8403

**Comment by GroundWalker7** [comment]
Hi again, I'm not familiar with DistributedDataParallel
What should I do if I want to resume training from .pth file?
Just simplely add torch.load() in function DDPMixSolver.train() ?

**Comment by GroundWalker7** [comment]
> Hi again, I'm not familiar with DistributedDataParallel
> What should I do if I want to resume training from .pth file?
> Just simplely add torch.load() in function DDPMixSolver.train() ?

Sry, I just realize that there was a `eval.py` in this repo

**Comment by GroundWalker7** [comment]
您好，方便加个微信吗，我最近用您的代码训练出来效果不是很好

**Comment by liangheming** [comment]
2605400720@qq.com，邮件发送 请查收

**Comment by J-xinyu** [comment]
您好，我用的是一个GPU，多次尝试修改您的代码未果，可以加微信聊一下吗，或者您如果有单GPU的训练代码可以方便提供一下吗

**Comment by J-xinyu** [comment]
并且我运行main函数的时候会出现RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`这个报错
